name: Docker Image CI for GHCR

on: 
  push

jobs:
  build_and_publish:
    run-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Build and push the images
        run: |
          docker login --username achmadsyafawi --password ${{secret.GH}} ghcr.io
          docker build . --tag ghcr.io/achmadsyafawi/headless-cms-blog:latest
          docker push ghcr.io/achmadsyafawi/headless-cms-blog:latest
